name: "chore"
on: workflow_dispatch

jobs:
  test-extension:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-12, ubuntu-22.04, windows-latest ]
    steps:
      - uses: smallstepman/cargo-binstall@main
      - run: cargo binstall -y ripgrep
      - run: rg --help
