name: "chore"
on: 
  workflow_dispatch:
    inputs:
      updateNnsCanisters:
        description: 'ya'
        type: boolean
        default: true

jobs:
  update-replica:
    runs-on: ubuntu-latest
    steps:
    - name: work?
      run: |
        echo "cece" > xyyx
        shasum -a 256 xyyx
